module com.example.lab5gui {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.web;
    requires org.controlsfx.controls;
    requires com.dlsc.formsfx;
    requires net.synedra.validatorfx;
    requires org.kordamp.ikonli.javafx;
    requires org.kordamp.bootstrapfx.core;
    requires com.almasb.fxgl.all;
    requires com.fasterxml.jackson.databind;
    requires static lombok;
    requires MyLibrary;
    requires java.sql;
    requires java.persistence;
    requires java.naming;
    requires spring.core;
    requires spring.boot;
    requires org.hibernate.orm.core;
    requires static javassist;
    requires spring.data.jpa;
    requires spring.data.commons;
    requires spring.beans;
    requires spring.context;
    requires spring.boot.autoconfigure;
    opens com.example.lab5gui to javafx.fxml, spring.core;
    exports com.example.lab5gui;
    exports com.example.lab5gui.controllers;
    opens com.example.lab5gui.controllers to javafx.fxml;
    exports com.example.lab5gui.entities;
    opens com.example.lab5gui.entities to javafx.fxml;
    exports com.example.lab5gui.entities.master;
    opens com.example.lab5gui.entities.master to javafx.fxml;
    exports com.example.lab5gui.entities.ferret;
    opens com.example.lab5gui.entities.ferret to javafx.fxml;
}